# Run local standalone node
#
# edit '/etc/hosts', add following lines:
# 127.0.0.1 local-eureka



version: '2.1'
services:
  local-eureka:
    image: ${DOCKER_REGISTRY:-registry.docker.local}/oss-eureka:latest
    restart: always
    command: []
    container_name: local-eureka
    hostname: local-eureka
    ports:
    - "${EUREKA_INSTANCE_NONSECUREPORT:-8761}:8761"
    volumes:
    - local-eureka-volume:/root/data
    - local-eureka-volume:/tmp
    environment:
    - EUREKA_CLIENT_FETCHREGISTRY=false
    - EUREKA_CLIENT_REGISTERWITHEUREKA=false
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://${SECURITY_USER_NAME:-user}:${SECURITY_USER_PASSWORD:-user_pass}@local-eureka:${SERVER_PORT:-8761}/eureka/
    - EUREKA_INSTANCE_HOSTNAME=local-eureka
    #- EUREKA_INSTANCE_IP_ADDRESS=${HOST_IP_ADDRESS:-127.0.0.1}
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:-false}
    - EUREKA_INSTANCE_NONSECUREPORT=${EUREKA_INSTANCE_NONSECUREPORT:-8761}
    - PEER=standalone
    - SECURITY_BASIC_ENABLED=${SECURITY_BASIC_ENABLED:-false}
    - SECURITY_USER_NAME=${SECURITY_USER_NAME:-user}
    - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD:-user_pass}
    - SERVER_PORT=${SERVER_PORT:-8761}
    - SPRING_APPLICATION_NAME=eureka-standalone
    - SPRING_CLOUD_CLIENT_HOSTNAME=local-eureka
    #- SPRING_CLOUD_CLIENT_IP_ADDRESS=${HOST_IP_ADDRESS:-127.0.0.1}
    - SPRING_PROFILES_ACTIVE=development.env

volumes:
  local-eureka-volume: {}

networks:
  default:
    external:
      name: oss-network
